# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfcb9aae5dc6e2e192dc2e27d18a7dba458d24de85b57c57d0a131a29b2331baf2e0d372cbbec0c301d258b428af50761dc56f63beec1a7166d2095a9e8c4370

test:
  secret_key_base: dc88e4c8c650f8818ad0e577d83ac7a6b328e8bc8d7ea8c7a7e9418bd16d65ce90a3debf062c6acc8713925bea26ffb621ea0bb16d5d4b8d5b910308bc6fff27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
